export const ENDPOINTS = {
  login: '/login',
  createUser: '/users',
  showDrivers: '/drivers/list',
  createDriver: '/drivers',
  updateDriver: (id: number) => `/drivers?id=${id}`,
  createClient: '/clients',
  showClients: '/clients/list',
  updateClient: (id: number) => `/clients?id=${id}`,
  showCities: '/clients/cities',
  createBus: '/buses',
  showBus: '/buses/list',
  updateBus: (id: number) => `/buses?id=${id}`,
  createTravel: '/travels',
  updateTravel: (id: string) => `travels?id=${id}`,
  showTravels: 'travels/list', 
};
